# Generated by Django 5.0.7 on 2024-07-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='INTEGRADOR_CAT_ROLES',
        ),
    ]
