# Generated by Django 5.0.7 on 2024-07-21 01:27

import django.utils.timezone
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('git', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('video', models.FileField(upload_to=tasks.models.get_upload_path, validators=[tasks.models.validate_file_size])),
                ('archivo', models.FileField(upload_to=tasks.models.get_upload_path, validators=[tasks.models.validate_file_size])),
                ('done', models.BooleanField(default=False)),
                ('checkbox', models.CharField(choices=[('Integradores', 'Integradores'), ('Moviles', 'Móviles'), ('Global', 'Global'), ('Webs', 'Webs'), ('Proyectos', 'Proyectos')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
