# Generated by Django 5.0.7 on 2024-07-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='INTEGRADOR_CAT_TASK',
        ),
    ]
