# Generated by Django 4.2.4 on 2023-10-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_archivo_de_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='archivo_de_video',
            new_name='video',
        ),
    ]
