# Generated by Django 5.0.7 on 2024-07-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkbox',
            field=models.CharField(choices=[('integradores', 'Integradores'), ('moviles', 'Móviles'), ('webs', 'Webs'), ('proyectos', 'Proyectos'), ('global', 'Global')], max_length=50),
        ),
    ]
