# Generated by Django 4.2.4 on 2023-10-07 07:16

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_archivo_de_video_task_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archivo',
            field=models.FileField(default=100000, upload_to='Archivos/', validators=[tasks.models.validate_file_size]),
            preserve_default=False,
        ),
    ]
