# Generated by Django 4.2.4 on 2024-03-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='git',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
