/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ticketss;
import java.io.File;
import javax.swing.*;

public class Paraword extends javax.swing.JFrame {
    JFileChooser seleccionado =new JFileChooser();
    File archivo;
   Gestion ges=new Gestion();
    
   
    public Paraword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vista6 = new javax.swing.JTextField();
        vista1 = new javax.swing.JTextField();
        vista3 = new javax.swing.JTextField();
        vista2 = new javax.swing.JTextField();
        vista5 = new javax.swing.JTextField();
        vista7 = new javax.swing.JTextField();
        vista4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        vista8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vista9 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vista6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista6ActionPerformed(evt);
            }
        });
        getContentPane().add(vista6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 146, -1));

        vista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista1ActionPerformed(evt);
            }
        });
        getContentPane().add(vista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 146, -1));

        vista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista3ActionPerformed(evt);
            }
        });
        getContentPane().add(vista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 146, -1));

        vista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista2ActionPerformed(evt);
            }
        });
        getContentPane().add(vista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 146, -1));

        vista5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista5ActionPerformed(evt);
            }
        });
        getContentPane().add(vista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 146, -1));

        vista7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista7ActionPerformed(evt);
            }
        });
        getContentPane().add(vista7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 146, -1));

        vista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista4ActionPerformed(evt);
            }
        });
        getContentPane().add(vista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 146, -1));

        jButton4.setBackground(new java.awt.Color(102, 255, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Abrir documento ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, -1));

        vista8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vista8ActionPerformed(evt);
            }
        });
        getContentPane().add(vista8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 146, -1));

        vista9.setColumns(20);
        vista9.setRows(5);
        jScrollPane1.setViewportView(vista9);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Folio ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 69, -1));

        jLabel2.setBackground(new java.awt.Color(0, 153, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vendedor ");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 69, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 520, 460));

        jLabel4.setBackground(new java.awt.Color(0, 153, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Comprador ");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 69, -1));

        jLabel5.setBackground(new java.awt.Color(0, 153, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descripción ");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 69, -1));

        jLabel6.setBackground(new java.awt.Color(0, 153, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Hora ");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 69, -1));

        jLabel7.setBackground(new java.awt.Color(0, 153, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 69, -1));

        jLabel8.setBackground(new java.awt.Color(0, 153, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total a pagar ");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, -1));

        jLabel9.setBackground(new java.awt.Color(0, 153, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio por Kg");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, -1));

        jLabel10.setBackground(new java.awt.Color(0, 153, 255));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Peso del Bovino");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ticketss/Captura de pantalla 2023-11-21 221401.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vista6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista6ActionPerformed

    private void vista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista1ActionPerformed

    private void vista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista3ActionPerformed

    private void vista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista2ActionPerformed

    private void vista5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista5ActionPerformed

    private void vista7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista7ActionPerformed

    private void vista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista4ActionPerformed

    private void vista8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vista8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vista8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if (seleccionado.showDialog(this,"ABRIR ARCHIVO")==JFileChooser.APPROVE_OPTION){
    archivo=seleccionado.getSelectedFile();
    if(archivo.canRead());
    if(archivo.getName().endsWith("txt")){
        String contenido = ges.AbrirTexto(archivo);
        txtArea.setText(contenido);
    }
}     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Problema we=new Problema();
        we.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (seleccionado.showDialog(null,"GUARDAR TEXTO ")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionado.getSelectedFile();
            if (archivo.getName().endsWith("txt")){
                String contenido=txtArea.getText();
                String respuesta=ges.GuaradarATexto(archivo,contenido);
                if(respuesta!=null){
                    JOptionPane.showMessageDialog(null, respuesta);
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar el documento.");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Este es unm formato de tipo texto." );
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paraword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paraword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paraword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paraword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paraword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    public static javax.swing.JTextField vista1;
    public static javax.swing.JTextField vista2;
    public static javax.swing.JTextField vista3;
    public static javax.swing.JTextField vista4;
    public static javax.swing.JTextField vista5;
    public static javax.swing.JTextField vista6;
    public static javax.swing.JTextField vista7;
    public static javax.swing.JTextField vista8;
    public static javax.swing.JTextArea vista9;
    // End of variables declaration//GEN-END:variables
}
